name: License Check
on: 
  push:

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout recursive
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: License check
        uses: apache/skywalking-eyes@main
